### ISSUE TITLE
Naming presets

### ISSUE THREAD

**Issue by Tagirijus** [almarklein/timetagger#469] opened 2024-04-18 09:39 UTC
It would be nice to be able to name presets.

When working with more than just a few tags for frequent tasks and having a preset for such, the preset dropdown can get crowded and unclear to read. Maybe the actual preset manager could be extended to handle strings with a colon at the beginning to describe the preset name or so:

```
presetname a:#client #project #other #tags #going #here
presetname b:#client-b #project-c #other #similar #tags #going #here
...
```

And then in the dropdown you could also search for the presetname as well, yet on choosing it would enter the tags only and not the presetname, of course.

Edit: Oh, this also might a bit related to #445

**Comment by almarklein** [comment] 2024-04-19 11:07
Good point, but kind of a duplicate of #445, yeah

**Closed by almarklein** 2024-04-19 11:07 UTC
