### ISSUE TITLE
Full width layout

### ISSUE THREAD

**Issue by boehs** [almarklein/timetagger#162] opened 2022-02-13 02:25 UTC
Currently max width of canvas is 1024px, would be nice if I could opt to have it be the full screen width. I tried to figure this out in code but no luck :(

**Comment by almarklein** [comment] 2022-02-13 10:48
Worth looking into, but I'm not sure if full width would make the app more useful/pretty. That said, being able to make it wider than it is now seems reasonable.

**Comment by GitHofi** [comment] 2022-02-14 08:50
That, I would also like, especially if more of the log text would then be readable.
Currently I can only see 2 tags and hardly anything of the text
<img width="255" alt="2022_0214_0948_01" src="https://user-images.githubusercontent.com/12327228/153830460-efeb8414-9485-4085-a9a0-615de91971bb.png">
.

**Comment by almarklein** [comment] 2022-03-16 11:36
Closed by #171

**Comment by eldelacajita** [comment] 2022-03-18 07:53
Hi, Almar. This is a welcome improvement!

I was actually hoping for a completely no-margin option. This is my use case: 

I use TimeTagger as a standalone web app (using Web browser on Gnome, Linux). When the window is small and there are no margins, it looks awesome: 

![imagen](https://user-images.githubusercontent.com/2880679/158959113-d2d1a737-c908-4349-84d1-8614eb05eaae.png)

But when I snap the window to the full width of my screen (1200 px, because it's a vertical monitor),  the margin appears and it looks less like an app and more like a web inside a frame.

![imagen](https://user-images.githubusercontent.com/2880679/158958334-d1735398-e114-4086-b8f3-4e2b508485b8.png)

Also removing the lower margin would be great, but I can live with that. I mean, I can live with both, actually :smile: It's just a small visual and functional improvement (extra text visible in the records).

**Comment by almarklein** [comment] 2022-03-18 22:15
Ok, I see your point. I'm starting to think that this needs to be configurable, preferably using a sash/button near the edge of the screen.

I don't understand why there is a margin at the bottom. That should not be there, and I cannot reproduce it (tried installing as an app in Chrome, but I see no margin at the bottom.)

**Comment by almarklein** [comment] 2022-04-27 13:39
> I don't understand why there is a margin at the bottom.

This looks like #194, and should probably be fixed with #198.

**Closed** 2022-06-04 19:47 UTC
Labels: Idea

**Comment by almarklein** [comment] 2022-06-09 08:07
Released and deployed!

**Comment by eldelacajita** [comment] 2022-06-09 10:44
Yay! Thanks a lot, I'm loving it :heart_eyes:
